server:
 port: 8888

#spring:
# profiles:
#  active: native
# cloud:
#  config:
#   server:
#    native:
#     search-locations: classpath:/config
     
spring:
 cloud:
  config:
   server:
    git: 
     uri: https://gitlab.com/sivakrishna4/mini_cricket_proj01.git
     username: sivakrishnavelpula
     password: velpulasi1@2